# Introducción a las herramientas del cómputo científico.

### Sergio A. Alcalá Corona 
---
---

## Producto Vectorial y Matricial.
---


In [1]:
import numpy as np

In [175]:
v1 = [7.,10.]
v2 = [5.,3.]

In [176]:
p = v1[0]*v2[0] + v1[1]*v2[1]
p

65.0

In [177]:
v4 = [7.,10.,3.]
v5 = [5.,3.,2.]
b = v4[0]*v5[0] + v4[1]*v5[1]+ v4[2]*v5[2]
b 

71.0

In [178]:
def ProdInt(v1,v2):
    a = 0.0
    if len(v1) != len(v2):
        print("Vectores de Diferente dimension")
#         print len(v1), len(v2)
    else:
        dim = len(v1)
        
        for i in range(dim):
            a = a + v1[i]*v2[i]
            
    return a

In [179]:
v1 = [7.,10.]
v2 = [5.,3.]

ProdInt(v1,v2)

65.0

In [180]:
A = [v1,v2]
# A = np.array([v1,v2])

A

[[7.0, 10.0], [5.0, 3.0]]

In [181]:
x1 = [3,4]

In [63]:
len(A[0])

2

In [182]:
def Prod(A,x):
    v = []
    dim = len(A)
    if len(A[0]) != len(x):
        print("No se puede!")
    else:
        for i in range(dim):
            v.append(ProdInt(A[i],x))
            
    return v

In [183]:
Prod(A,x1)

[61.0, 27.0]

In [135]:
v = []

In [136]:
A = [v1,v2]

In [184]:
a1 = [1,2]
a2 = [4,5]
a3 = [7,8]

In [190]:
A = [a1,a2,a3]
# A = np.array([a1,a2,a3])
A

[[1, 2], [4, 5], [7, 8]]

In [191]:
b1 = [1,2,3]
b2 = [0,5,2]

In [193]:
B = [b1,b2]
# B = np.array([b1,b2])
B

[[1, 2, 3], [0, 5, 2]]

In [188]:
# len(B[0])
# len(A)

In [197]:
R = [[1, 2, 3], [0, 5, 2], [3, 2, 1]]
K = [[5, 4, 1], [0, 1, 0], [1, 2, 3]]

R = np.array([[1, 2, 3], [0, 5, 2], [3, 2, 1]])
K = np.array([[5, 4, 1], [0, 1, 0], [1, 2, 3]])

R

array([[1, 2, 3],
       [0, 5, 2],
       [3, 2, 1]])

In [198]:
K

array([[5, 4, 1],
       [0, 1, 0],
       [1, 2, 3]])

In [208]:
C

[[1, 2], [4, 5], [7, 8], [11, 12]]

In [199]:
def renglones(X):
    rens = []
    for i in range(len(X)):
        rens.append(X[i])
    
    return rens

In [200]:
def columnas(X):
    cols = []
    for i in range(len(X[0])):
        vT = []
        for j in range(len(X)):
            vT.append(X[j][i])
        cols.append(vT)
                   
    return cols

In [214]:
np.array(C)

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [11, 12]])

In [220]:
renglones(A)

[[1, 2], [4, 5], [7, 8]]

In [219]:
columnas(C)

[[1, 4, 7, 11], [2, 5, 8, 12]]

In [203]:
def ProdMat(A,B):
    Resultante = []
    ranA = len(renglones(A)[0])
    ranB = len(columnas(B)[0])
    if ranA != ranB:
        print("No se puede!")
    else:
        for ren in renglones(A):
            v = []
            for col in columnas(B):
                v.append(ProdInt(ren,col))
            Resultante.append(v)
            
    return Resultante

In [221]:
A

[[1, 2], [4, 5], [7, 8]]

In [222]:
B

[[1, 2, 3], [0, 5, 2]]

In [223]:
C = [[1, 2], [4, 5], [7, 8],[11,12]]
C

[[1, 2], [4, 5], [7, 8], [11, 12]]

In [224]:
R

array([[1, 2, 3],
       [0, 5, 2],
       [3, 2, 1]])

In [225]:
K

array([[5, 4, 1],
       [0, 1, 0],
       [1, 2, 3]])

In [168]:
print "Dim(A) = ",len(A),"x",len(A[0])
print "Dim(B) = ",len(B),"x",len(B[0])
print "Dim(C) = ",len(C),"x",len(C[0])
print "Dim(R) = ",len(R),"x",len(R[0])
print "Dim(K) = ",len(K),"x",len(K[0])

Dim(A) =  3 x 2
Dim(B) =  2 x 3
Dim(C) =  4 x 2
Dim(R) =  3 x 3
Dim(K) =  3 x 3


In [232]:
ProdMat(R,K)

[[8.0, 12.0, 10.0], [2.0, 9.0, 6.0], [16.0, 16.0, 6.0]]

In [233]:
np.dot(R,K)

array([[ 8, 12, 10],
       [ 2,  9,  6],
       [16, 16,  6]])

In [169]:
print renglones(C)

[[1, 2], [4, 5], [7, 8], [11, 12]]


In [170]:
print columnas(B)

[[1, 0], [2, 5], [3, 2]]


In [171]:
ProdMatB(C,B)

[[1.0, 12.0, 7.0], [4.0, 33.0, 22.0], [7.0, 54.0, 37.0], [11.0, 82.0, 57.0]]

In [172]:
np.dot(C,B)

array([[ 1, 12,  7],
       [ 4, 33, 22],
       [ 7, 54, 37],
       [11, 82, 57]])

In [173]:
# np.dot(B,C)

In [174]:
# ProdMatB(A,B)
ProdMatB(B,A)

[[30.0, 36.0], [34.0, 41.0]]

In [159]:
np.dot(A,B)

array([[ 1, 12,  7],
       [ 4, 33, 22],
       [ 7, 54, 37]])

In [160]:
ProdMatB(K,R)

[[8.0, 32.0, 24.0], [0.0, 5.0, 2.0], [10.0, 18.0, 10.0]]

In [161]:
np.dot(K,R)

array([[ 8, 32, 24],
       [ 0,  5,  2],
       [10, 18, 10]])